---
driver:
  name: docker
  use_sudo: false

platforms:
  - name: centos-7.2
    driver_config:
      image: ansible/centos7-ansible:stable

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_verbose: true
  ansible_verbosity: 2
  require_ansible_repo: true
  require_ansible_omnibus: true
  require_chef_for_busser: false


verifier:
  name: serverspec
  bundler_path: '/usr/local/bin'
  rspec_path: '/usr/local/bin'
  ruby_bindir: '/usr/bin'

suites:
  - name: centos
    verifier:
      patterns:
        - roles/docker-test-kitchen/test/integration/spec/centos_spec.rb
